baseURL: https://dehsi2022.netlify.app/
languageCode: en-us
defaultContentLanguage: en
title: Digital Education Hub Summer Institute 2022
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

#permalinks:
#  post: /:filename/

imaging:
  quality: 99

params:
  description: The Digital Education Hub Summer Institute Online Workbook.
  homeMetaContent: The Digital Education Hub Summer Institute Online Workbook.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false
  logoAlt: "DEH Summer Institute Logo"
  customCss:
    - css/all.css
  #  - css/brands.css
  #  - css/custom_02.css
  customJs:
    - js/all.js
  #  - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Background
      url: /background/
      weight: 2
    - name: Session 1
      url: /session1/
      weight: 3
    - name: Session 2
      url: /session2/
      weight: 4
    - name: Session 3
      url: /session3/
      weight: 5
    - name: Session 4
      url: /session4/
      weight: 6
    - name: Session 5
      url: /session5/
      weight: 7
    - name: Session 6
      url: /session6/
      weight: 8
    - name: Session 7
      url: /session7/
      weight: 9
    - name: Session 8
      url: /session8/
      weight: 10
    - name: Session 9
      url: /session9/
      weight: 11

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
